### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by ashutosh4336** [UltimateHackers/Jio-Fucker#1]
It doesn't work 

Traceback (most recent call last):
  File "jio.py", line 44, in <module>
    ping()
  File "jio.py", line 6, in ping
    result = urlopen("http://magicapk.com/jiosimdetail.php", data)
  File "/usr/lib/python2.7/urllib.py", line 89, in urlopen
    return opener.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 215, in open
    return getattr(self, name)(url, data)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 111] Connection refused

**Comment by UltimateHackers** [comment]
Repo's readme clearly states that it doesn't work now as the source has been taken down.
